version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
